screener_equities:
  tickers:
  - AAPL
  - MSFT
  - TSLA
  - NVDA
  - AMD
  - META
  - AMZN
  - GOOGL
  - SMCI
  - NFLX
  - QQQ
  - SPY
  lookback_days: 120
  min_price: 3
  min_avg_volume: 1000000
  top_n: 10
  score_weights:
    momentum: 0.45
    volatility: 0.2
    liquidity: 0.2
    trend_quality: 0.15
  atr_mult_target: 2.5
screener_crypto:
  tickers:
  - BTC-USD
  - ETH-USD
  - SOL-USD
  - AVAX-USD
  - DOGE-USD
  - XRP-USD
  - ADA-USD
  - LINK-USD
  lookback_days: 120
  top_n: 10
  score_weights:
    momentum: 0.55
    volatility: 0.25
    liquidity: 0.15
    trend_quality: 0.05
  atr_mult_target: 3.0
backtest:
  tickers:
  - AAPL
  - MSFT
  - TSLA
  lookback_days: 10
  or_minutes: 15
  ema_period: 20
  atr_period: 14
  atr_mult: 2.0
  allow_short: true
  starting_capital: 100000
  risk_per_trade: 0.005
  end_liquidate: '15:55'
watchlist:
  tickers:
  - AAPL
  - NVDA
  - TSLA
  - SPY
  - QQQ
  - BTC-USD
  - ETH-USD
  interval: 1h
  lookback_days: 90
ai:
  tickers:
  - AAPL
  - NVDA
  - TSLA
  - SPY
  - BTC-USD
  - ETH-USD
  interval: 15m
  lookback_days: 90
  train_epochs: 250
  lr: 0.2
  l2: 0.0001
  buy_threshold: 0.6
  sell_threshold: 0.4
